name = "app-store-price"
main = "src/worker.ts"
compatibility_date = "2026-04-21"
workers_dev = false
routes = [
  { pattern = "appprice.xinrong.org/*", zone_name = "xinrong.org" }
]

[assets]
directory = "./public"

[triggers]
crons = ["0 2 * * *"]

[[kv_namespaces]]
binding = "APP_CACHE"
id = "685a4965b7fe42d9ae3bbc1d46d5f14f"
preview_id = "f3be72249fb84201af7bd1016fd56fd2"

[[kv_namespaces]]
binding = "FX_CACHE"
id = "b31b8a71e5c0463a8928a0f7a2ed810e"
preview_id = "754d5a92d6934b39a3cc4e7b6fd51ed1"
